
    <div class="row">
        <div class="col l8 offset-l2 s12 ">
            <div class="card center">
                <div class="card-image ">
                <img src="public\img\lawfirm2.jpg">
                <span class="card-title">Welcome</span>
                </div>
                <div class="card-content">
                <p>Since established in 1995, Law office offers a full range of legal advise and services
    of highest business standards to domestic and international clients.

    We focus our activities on legal consultancy in the fields of corporate & commercial law, 
    M&A, real estate, capital markets, banking & finance, competition law, privatisation, 
    project finance, telecommunications and media law, labor law, intellectual property and dispute resolution.

    For additional information about our Office or in case of your interest for business cooperation, please contact us..</p>
                </div>
                <div class="card-action">
                <a href="app\view\kontakt.phtml">Contact us</a>
                </div>
            </div>
            </div>
        </div>
