<meta charset="utf-8">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title><?php echo App::config("nazivApp"); ?></title>
<link rel="stylesheet" href="<?php echo App::config("url") ?>public\css\materialize.css">
<link rel="stylesheet" href="<?php echo App::config("url") ?>public\css\materialize.min.css">
<link rel="stylesheet" href="<?php echo App::config("url") ?>public\css\app.css">
<script src="https://kit.fontawesome.com/3b8c308efb.js"></script>