
        <form method="post" 
            action="<?php echo App::config("url")?>legal_case_trainees/promjeni/<?php echo $id ?>">
                <?php include_once 'detalji.phtml' ?>
                     <div class="row">
                     <div class="col l3 offset-l3 s6">
                            
                                <a class="btn btn-block waves-light"
                                    href="<?php echo App::config("url")?>legal_case_trainees/index">
                                    Back
                                </a>
                            </div>
                            <div>
                            <div class="row">
                             <div class="col l3 s6">
                                <input class="btn btn-block white-text waves-light"
                                    type="submit" value="Change legal case trainees">
                            </div>
                </div>       
        </form>
