
<form method="post" 
    action="<?php echo App::config("url")?>clients/promjeni/<?php echo $id ?>">
        <?php include_once 'detalji.phtml' ?>
                    
        <div class="row">
            <div class="col l3 offset-l3 s6">
                <a class="btn btn-block waves-light"
                     href="<?php echo App::config("url")?>clients/index"> Back
                </a>
            </div>

            <div class="row">    
                <div class="col l3 s6">
                    <input class="btn btn-block white-text waves-light"
                    type="submit" value="Change client">
                </div>           
            </div>
        </div>

</form>

