<a href="<?php echo App::config("url") ?>lawyers/pripremaNovi" 
class="btn btn-block waves-effect waves-light">
<i class="material-icons left"></i> Add new lawyer</a>
</a>
<div id="container">
  <div class="row">
        <?php foreach($lawyers as $lawyer): ?>
          <div class="col s12 m4 grey lighten-4">
            <div class= "center-align">
              <div class="card">
                <div class="card-content">
                    <div class="card-title grey lighten-4 black-text">
                    <h5>Lawyer information</h5>
                    </div>
                    <img src="<?php echo App::config("url") ?>public/img/nepoznataOsoba.png">
                    <ul class="collection">
                    <li>Firstname: <?php echo $lawyer->firstname?></li>
                    <li>Lastname: <?php echo $lawyer->lastname?></li>
                    <li>OIB: <?php echo $lawyer->OIB?></li>
                    <li>IBAN: <?php echo $lawyer->IBAN?></li>
                    </ul>

                      <div>
                    
                      <a title="Obriši <?php echo $lawyer->lawyer_id ?>" 
                      onclick="return confirm('Sigurno obrisati <?php echo $lawyer->lawyer_id ?>?');"
                      href="<?php 
                      echo App::config("url") 
                      ?>lawyers/brisanje/<?php echo $lawyer->lawyer_id ?>">
                      
                      <div class="btn btn-block btn-large red accent-2">Delete lawyer</div>
                      </a>
                      <a title="promjeni <?php echo $lawyer->firstname ?>" 
                      href="<?php echo App::config("url")?>lawyers/pripremaPromjeni/
                      <?php echo $lawyer->lawyer_id ?>">
                      <div class="btn btn-block btn-large yellow accent-4">Change information</div>
                      </a>
                         
                  </div>
                </div>
              </div>
            </div>
          </div>
        <?php endforeach;?>  
  </div>
</div>

