
            <form method="post" 
            action="<?php echo App::config("url")?>lawyers/novi">
            <?php include_once 'detalji.phtml' ?>

                <div class="row">
                <div class="col l3 offset-l3 s6">
                <a class="btn btn-block waves-light"
                href="<?php echo App::config("url")?>lawyers/index">
                    Back to lawyers
                </a>
                </div>
                    <div class="row">
                        <div class="col l3 s6">
                        <input class="btn btn-block white-text waves-light "
                        type="submit" value="Add new Lawyer">
                    </div>
                </div>
            <form>
